name: Deploy Storybook to GitHub Pages
description: Build and deploy storybook to GitHub pages
outputs:
  page_url:
    description: The URL of the page
    value: ${{ steps.deploy.outputs.page_url }}

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Build storybook
      shell: bash
      run: |
        pnpm install
        pnpm storybook:build
    - name: Upload storybook
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/storybook/docs
    - id: deploy
      name: Deploy storybook to github pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ github.token }}
